version: '2'

services:
  backend:
     depends_on:
       - mysql
     links:
       - mysql:mysql
     image: node:7
     user: "node"
     working_dir: /home/node/app
     volumes:
       - ./server/:/home/node/app
     ports:
       - "8500:8080"
     restart: always
     environment:
       DB_USER: root
       DB_PASS: passworddev
       PORT: 8080
     command: "node index.js"

  mysql:
     image: mysql:5.7
     ports:
       - "8501:3306"
     volumes:
       - mysqldata:/var/lib/mysql
     restart: always
     environment:
       WORDPRESS_DB_USER: dbuser
       MYSQL_ROOT_PASSWORD: passworddev
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: passworddev

volumes:
    mysqldata:
